### ISSUE TITLE
unsupported system error/bindeps config not correct

### ISSUE THREAD

**Issue by katieemelianova** [cboursnell/crb-blast#15]
I'm getting an error that seems to be to do with blastplus and an unsupported system error.
I'm on a mac and running Ruby v 2.3.0 and blastn: 2.10.0+.

I installed crb-blast as specified without any problems. My command and the resulting error (and a gem warning) is:

crb-blast -q con_Trinity.longest.fasta -t ple_Trinity.longest.fasta -o con_ple_rbh_1e-5

[DEPRECATION] The trollop gem has been renamed to optimist and will no longer be supported. Please switch to optimist as soon as possible.
/Library/Ruby/Gems/2.3.0/gems/bindeps-1.2.1/lib/bindeps.rb:103:in `choose_url': bindeps config for blastplus doesn't contain an entry for 32bit (Bindeps::UnsupportedSystemError)
	from /Library/Ruby/Gems/2.3.0/gems/bindeps-1.2.1/lib/bindeps.rb:77:in `initialize'
	from /Library/Ruby/Gems/2.3.0/gems/bindeps-1.2.1/lib/bindeps.rb:23:in `new'
	from /Library/Ruby/Gems/2.3.0/gems/bindeps-1.2.1/lib/bindeps.rb:23:in `block (3 levels) in require'
	from /Library/Ruby/Gems/2.3.0/gems/bindeps-1.2.1/lib/bindeps.rb:20:in `each_pair'
	from /Library/Ruby/Gems/2.3.0/gems/bindeps-1.2.1/lib/bindeps.rb:20:in `block (2 levels) in require'
	from /Library/Ruby/Gems/2.3.0/gems/bindeps-1.2.1/lib/bindeps.rb:19:in `chdir'
	from /Library/Ruby/Gems/2.3.0/gems/bindeps-1.2.1/lib/bindeps.rb:19:in `block in require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/tmpdir.rb:89:in `mktmpdir'
	from /Library/Ruby/Gems/2.3.0/gems/bindeps-1.2.1/lib/bindeps.rb:18:in `require'
	from /Library/Ruby/Gems/2.3.0/gems/crb-blast-0.6.9/bin/crb-blast:63:in `<top (required)>'
	from /usr/local/bin/crb-blast:22:in `load'
	from /usr/local/bin/crb-blast:22:in `<main>'

**Comment by jsevereyn** [comment]
Hello, were you able to fix this error?

I'm struggling with the exact same right now

**Comment by katieemelianova** [comment]
Unfortunately not - based on the last commits being in 2017 I'm guessing its no longer being contributed to.

**Comment by jsevereyn** [comment]
I just managed to make it work by downgrading Blast to a version from around that date (as apparently it ask for Blast v2.3.29). Because I love CRB-Blast and I had it running for a long time on my old computer.

I follow these steps in a conda environment

conda create --name crb-blast
conda activate crb-blast
conda install -c bioconda blast=2.2.31
conda install -c conda-forge ruby
gem install crb-blast

and it worked like a charm

**Comment by katieemelianova** [comment]
Aha! Good to know, thanks for that. I ended up just implementing my own method but this would be much less faff :)

**Comment by gcambray** [comment]
@jsevereyn : got the exact same issue and followed your suggestion without luck, still the same error. Weird... Tried installing other blast version as well with no effect.
@blahah : maybe you can suggest something ?

**Comment by jsevereyn** [comment]
Yeah it worked for me at that time..... But now its not working again

is sad to lose this tool as I haven't find any other better to carry out local blast in such easy way

**Comment by gcambray** [comment]
@jsevereyn : you might be interested in this https://github.com/glarue/reciprologs

**Comment by jsevereyn** [comment]
It worked today, I just install it with Conda
`conda install bioconda::crb-blast`

With [reciprologs](https://github.com/glarue/reciprologs) I was never able to get the palign recognized, I'm not a programmer at all, so the $PATH variable is an advanced field for me.
I work on a Mac with zsh
